/* This program is released under the GPL (v2) license by Katsumi. */
if (!window.JSSpeccy) window.JSSpeccy = {};
(function(window){

	var ld ="LD    ";
	var bit='BIT   ';
	var res='RES   ';
	var set='SET   ';
	var rlc="RLC   ";
	var rrc="RRC   ";
	var rl ="RL    ";
	var rr ="RR    ";
	var sla="SLA   ";
	var sra="SRA   ";
	var sll="SLL   ";
	var srl="SRL   ";

	var code1 =["NOP","",ld+"(BC),A","INC   BC","INC   B","DEC   B","","RLCA","EX    AF,AF'",
				"ADD   HL,BC",ld+"A,(BC)","DEC   BC","INC   C","DEC   C","","RRCA","","",
				ld+"(DE),A","INC   DE","INC   D","DEC   D","","RLA","","ADD   HL,DE",ld+"A,(DE)",
				"DEC   DE","INC   E","DEC   E","","RRA","","","","INC   HL","INC   H","DEC   H","",
				"DAA","","ADD   HL,HL","","DEC   HL","INC   L","DEC   L","","CPL","","","","INC   SP",
				"INC   (HL)","DEC   (HL)","","SCF","","ADD   HL,SP","","DEC   SP","INC   A","DEC   A",
				"","CCF",ld+"B,B",ld+"B,C",ld+"B,D",ld+"B,E",ld+"B,H",ld+"B,L",
				ld+"B,(HL)",ld+"B,A",ld+"C,B",ld+"C,C",ld+"C,D",ld+"C,E",ld+"C,H",
				ld+"C,L",ld+"C,(HL)",ld+"C,A",ld+"D,B",ld+"D,C",ld+"D,D",ld+"D,E",
				ld+"D,H",ld+"D,L",ld+"D,(HL)",ld+"D,A",ld+"E,B",ld+"E,C",ld+"E,D",
				ld+"E,E",ld+"E,H",ld+"E,L",ld+"E,(HL)",ld+"E,A",ld+"H,B",ld+"H,C",
				ld+"H,D",ld+"H,E",ld+"H,H",ld+"H,L",ld+"H,(HL)",ld+"H,A",ld+"L,B",
				ld+"L,C",ld+"L,D",ld+"L,E",ld+"L,H",ld+"L,L",ld+"L,(HL)",ld+"L,A",
				ld+"(HL),B",ld+"(HL),C",ld+"(HL),D",ld+"(HL),E",ld+"(HL),H",ld+"(HL),L",
				"HALT",ld+"(HL),A",ld+"A,B",ld+"A,C",ld+"A,D",ld+"A,E",ld+"A,H",ld+"A,L",
				ld+"A,(HL)",ld+"A,A","ADD   A,B","ADD   A,C","ADD   A,D","ADD   A,E","ADD   A,H",
				"ADD   A,L","ADD   A,(HL)","ADD   A,A","ADC   A,B","ADC   A,C","ADC   A,D","ADC   A,E",
				"ADC   A,H","ADC   A,L","ADC   A,(HL)","ADC   A,A","SUB   B","SUB   C","SUB   D","SUB   E",
				"SUB   H","SUB   L","SUB   (HL)","SUB   A","SBC   A,B","SBC   A,C","SBC   A,D","SBC   A,E",
				"SBC   A,H","SBC   A,L","SBC   A,(HL)","SBC   A,A","AND   B","AND   C","AND   D","AND   E",
				"AND   H","AND   L","AND   (HL)","AND   A","XOR   B","XOR   C","XOR   D","XOR   E","XOR   H",
				"XOR   L","XOR   (HL)","XOR   A","OR    B","OR    C","OR    D","OR    E","OR    H","OR    L",
				"OR    (HL)","OR    A","CP    B","CP    C","CP    D","CP    E","CP    H","CP    L","CP    (HL)",
				"CP    A","RET   NZ","POP   BC","","","","PUSH  BC","","RST   00","RET   Z","RET","","","","","",
				"RST   08","RET   NC","POP   DE","","","","PUSH  DE","","RST   10","RET   C","EXX","","","","","",
				"RST   18","RET   PO","POP   HL","","EX    (SP),HL","","PUSH  HL","","RST   20","RET   PE",
				"JP    (HL)","","EX    DE,HL","","","","RST   28","RET   P","POP   AF","","DI","","PUSH  AF",
				"","RST   30","RET   M",ld+"SP,HL","","EI","","","","RST   38"];
/*
	function code1(code){
	  switch(code){
	    case '00': return 'NOP';
	    case '02': return ld+'(BC),A';
	    case '03': return 'INC   BC';
	    case '04': return 'INC   B';
	    case '05': return 'DEC   B';
	    case '07': return 'RLCA';
	    case '08': return 'EX    AF,AF\'';
	    case '09': return 'ADD   HL,BC';
	    case '0A': return ld+'A,(BC)';
	    case '0B': return 'DEC   BC';
	    case '0C': return 'INC   C';
	    case '0D': return 'DEC   C';
	    case '0F': return 'RRCA';
	    case '12': return ld+'(DE),A';
	    case '13': return 'INC   DE';
	    case '14': return 'INC   D';
	    case '15': return 'DEC   D';
	    case '17': return 'RLA';
	    case '19': return 'ADD   HL,DE';
	    case '1A': return ld+'A,(DE)';
	    case '1B': return 'DEC   DE';
	    case '1C': return 'INC   E';
	    case '1D': return 'DEC   E';
	    case '1F': return 'RRA';
	    case '23': return 'INC   HL';
	    case '24': return 'INC   H';
	    case '25': return 'DEC   H';
	    case '27': return 'DAA';
	    case '29': return 'ADD   HL,HL';
	    case '2B': return 'DEC   HL';
	    case '2C': return 'INC   L';
	    case '2D': return 'DEC   L';
	    case '2F': return 'CPL';
	    case '33': return 'INC   SP';
	    case '34': return 'INC   (HL)';
	    case '35': return 'DEC   (HL)';
	    case '37': return 'SCF';
	    case '39': return 'ADD   HL,SP';
	    case '3B': return 'DEC   SP';
	    case '3C': return 'INC   A';
	    case '3D': return 'DEC   A';
	    case '3F': return 'CCF';
	    case '40': return ld+'B,B';
	    case '41': return ld+'B,C';
	    case '42': return ld+'B,D';
	    case '43': return ld+'B,E';
	    case '44': return ld+'B,H';
	    case '45': return ld+'B,L';
	    case '46': return ld+'B,(HL)';
	    case '47': return ld+'B,A';
	    case '48': return ld+'C,B';
	    case '49': return ld+'C,C';
	    case '4A': return ld+'C,D';
	    case '4B': return ld+'C,E';
	    case '4C': return ld+'C,H';
	    case '4D': return ld+'C,L';
	    case '4E': return ld+'C,(HL)';
	    case '4F': return ld+'C,A';
	    case '50': return ld+'D,B';
	    case '51': return ld+'D,C';
	    case '52': return ld+'D,D';
	    case '53': return ld+'D,E';
	    case '54': return ld+'D,H';
	    case '55': return ld+'D,L';
	    case '56': return ld+'D,(HL)';
	    case '57': return ld+'D,A';
	    case '58': return ld+'E,B';
	    case '59': return ld+'E,C';
	    case '5A': return ld+'E,D';
	    case '5B': return ld+'E,E';
	    case '5C': return ld+'E,H';
	    case '5D': return ld+'E,L';
	    case '5E': return ld+'E,(HL)';
	    case '5F': return ld+'E,A';
	    case '60': return ld+'H,B';
	    case '61': return ld+'H,C';
	    case '62': return ld+'H,D';
	    case '63': return ld+'H,E';
	    case '64': return ld+'H,H';
	    case '65': return ld+'H,L';
	    case '66': return ld+'H,(HL)';
	    case '67': return ld+'H,A';
	    case '68': return ld+'L,B';
	    case '69': return ld+'L,C';
	    case '6A': return ld+'L,D';
	    case '6B': return ld+'L,E';
	    case '6C': return ld+'L,H';
	    case '6D': return ld+'L,L';
	    case '6E': return ld+'L,(HL)';
	    case '6F': return ld+'L,A';
	    case '70': return ld+'(HL),B';
	    case '71': return ld+'(HL),C';
	    case '72': return ld+'(HL),D';
	    case '73': return ld+'(HL),E';
	    case '74': return ld+'(HL),H';
	    case '75': return ld+'(HL),L';
	    case '76': return 'HALT';
	    case '77': return ld+'(HL),A';
	    case '78': return ld+'A,B';
	    case '79': return ld+'A,C';
	    case '7A': return ld+'A,D';
	    case '7B': return ld+'A,E';
	    case '7C': return ld+'A,H';
	    case '7D': return ld+'A,L';
	    case '7E': return ld+'A,(HL)';
	    case '7F': return ld+'A,A';
	    case '80': return 'ADD   A,B';
	    case '81': return 'ADD   A,C';
	    case '82': return 'ADD   A,D';
	    case '83': return 'ADD   A,E';
	    case '84': return 'ADD   A,H';
	    case '85': return 'ADD   A,L';
	    case '86': return 'ADD   A,(HL)';
	    case '87': return 'ADD   A,A';
	    case '88': return 'ADC   A,B';
	    case '89': return 'ADC   A,C';
	    case '8A': return 'ADC   A,D';
	    case '8B': return 'ADC   A,E';
	    case '8C': return 'ADC   A,H';
	    case '8D': return 'ADC   A,L';
	    case '8E': return 'ADC   A,(HL)';
	    case '8F': return 'ADC   A,A';
	    case '90': return 'SUB   B';
	    case '91': return 'SUB   C';
	    case '92': return 'SUB   D';
	    case '93': return 'SUB   E';
	    case '94': return 'SUB   H';
	    case '95': return 'SUB   L';
	    case '96': return 'SUB   (HL)';
	    case '97': return 'SUB   A';
	    case '98': return 'SBC   A,B';
	    case '99': return 'SBC   A,C';
	    case '9A': return 'SBC   A,D';
	    case '9B': return 'SBC   A,E';
	    case '9C': return 'SBC   A,H';
	    case '9D': return 'SBC   A,L';
	    case '9E': return 'SBC   A,(HL)';
	    case '9F': return 'SBC   A,A';
	    case 'A0': return 'AND   B';
	    case 'A1': return 'AND   C';
	    case 'A2': return 'AND   D';
	    case 'A3': return 'AND   E';
	    case 'A4': return 'AND   H';
	    case 'A5': return 'AND   L';
	    case 'A6': return 'AND   (HL)';
	    case 'A7': return 'AND   A';
	    case 'A8': return 'XOR   B';
	    case 'A9': return 'XOR   C';
	    case 'AA': return 'XOR   D';
	    case 'AB': return 'XOR   E';
	    case 'AC': return 'XOR   H';
	    case 'AD': return 'XOR   L';
	    case 'AE': return 'XOR   (HL)';
	    case 'AF': return 'XOR   A';
	    case 'B0': return 'OR    B';
	    case 'B1': return 'OR    C';
	    case 'B2': return 'OR    D';
	    case 'B3': return 'OR    E';
	    case 'B4': return 'OR    H';
	    case 'B5': return 'OR    L';
	    case 'B6': return 'OR    (HL)';
	    case 'B7': return 'OR    A';
	    case 'B8': return 'CP    B';
	    case 'B9': return 'CP    C';
	    case 'BA': return 'CP    D';
	    case 'BB': return 'CP    E';
	    case 'BC': return 'CP    H';
	    case 'BD': return 'CP    L';
	    case 'BE': return 'CP    (HL)';
	    case 'BF': return 'CP    A';
	    case 'C0': return 'RET   NZ';
	    case 'C1': return 'POP   BC';
	    case 'C5': return 'PUSH  BC';
	    case 'C7': return 'RST   00';
	    case 'C8': return 'RET   Z';
	    case 'C9': return 'RET';
	    case 'CF': return 'RST   08';
	    case 'D0': return 'RET   NC';
	    case 'D1': return 'POP   DE';
	    case 'D5': return 'PUSH  DE';
	    case 'D7': return 'RST   10';
	    case 'D8': return 'RET   C';
	    case 'D9': return 'EXX';
	    case 'DF': return 'RST   18';
	    case 'E0': return 'RET   PO';
	    case 'E1': return 'POP   HL';
	    case 'E3': return 'EX    (SP),HL';
	    case 'E5': return 'PUSH  HL';
	    case 'E7': return 'RST   20';
	    case 'E8': return 'RET   PE';
	    case 'E9': return 'JP    (HL)';
	    case 'EB': return 'EX    DE,HL';
	    case 'EF': return 'RST   28';
	    case 'F0': return 'RET   P';
	    case 'F1': return 'POP   AF';
	    case 'F3': return 'DI';
	    case 'F5': return 'PUSH  AF';
	    case 'F7': return 'RST   30';
	    case 'F8': return 'RET   M';
	    case 'F9': return ld+'SP,HL';
	    case 'FB': return 'EI';
	    case 'FF': return 'RST   38';
	    default:   return '';
	  }
	}
*/
	function code2(code,p1,addr){
	  var rel=parseInt('0x'+p1,16);
	  if (rel<128) rel=rel+addr+2;
	  else rel=rel+addr-256+2;
	  rel='000'+rel.toString(16);
	  rel=rel.substr(rel.length-4,4).toUpperCase();
	  switch(code){
	    case '10': return 'DJNZ  '+rel;
	    case '18': return 'JR    '+rel;
	    case '20': return 'JR    NZ,'+rel;
	    case '28': return 'JR    Z,'+rel;
	    case '30': return 'JR    NC,'+rel;
	    case '38': return 'JR    C,'+rel;
	    case '06': return ld+'B,'+p1;
	    case '0E': return ld+'C,'+p1;
	    case '16': return ld+'D,'+p1;
	    case '1E': return ld+'E,'+p1;
	    case '26': return ld+'H,'+p1;
	    case '2E': return ld+'L,'+p1;
	    case '36': return ld+'(HL),'+p1;
	    case '3E': return ld+'A,'+p1;
	    case 'C6': return 'ADD   A,'+p1;
	    case 'CE': return 'ADC   A,'+p1;
	    case 'D3': return 'OUT   ('+p1+'),A';
	    case 'D6': return 'SUB   '+p1;
	    case 'DB': return 'IN    A,('+p1+')';
	    case 'DE': return 'SBC   A,'+p1;
	    case 'E6': return 'AND   '+p1;
	    case 'EE': return 'XOR   '+p1;
	    case 'F6': return 'OR    '+p1;
	    case 'FE': return 'CP    '+p1;
	    case 'CB': return codeCB(code,p1);
	    case 'DD': return codeXD2(code,p1);
	    case 'ED': return codeED(code,p1);
	    case 'FD': return codeXD2(code,p1);
	    default:   return '';
	  }
	}
	function code3(code,p1,p2){
		var p2p1 = p2+p1;
	  switch(code){
	    case '01': return ld+'BC,'+p2p1;
	    case '11': return ld+'DE,'+p2p1;
	    case '21': return ld+'HL,'+p2p1;
	    case '22': return ld+'('+p2p1+'),HL';
	    case '2A': return ld+'HL,('+p2p1+')';
	    case '31': return ld+'SP,'+p2p1;
	    case '32': return ld+'('+p2p1+'),A';
	    case '3A': return ld+'A,('+p2p1+')';
	    case 'C2': return 'JP    NZ,'+p2p1;
	    case 'C3': return 'JP    '+p2p1;
	    case 'C4': return 'CALL  NZ,'+p2p1;
	    case 'CA': return 'JP    Z,'+p2p1;
	    case 'CC': return 'CALL  Z,'+p2p1;
	    case 'CD': return 'CALL  '+p2p1;
	    case 'D2': return 'JP    NC,'+p2p1;
	    case 'D4': return 'CALL  NC,'+p2p1;
	    case 'DA': return 'JP    C,'+p2p1;
	    case 'DC': return 'CALL  C,'+p2p1;
	    case 'E2': return 'JP    PO,'+p2p1;
	    case 'E4': return 'CALL  PO,'+p2p1;
	    case 'EA': return 'JP    PE,'+p2p1;
	    case 'EC': return 'CALL  PE,'+p2p1;
	    case 'F2': return 'JP    P,'+p2p1;
	    case 'F4': return 'CALL  P,'+p2p1;
	    case 'FA': return 'JP    M,'+p2p1;
	    case 'FC': return 'CALL  M,'+p2p1;
	    case 'DD': return codeXD3(code,p1,p2);
	    case 'ED': return '';
	    case 'FD': return codeXD3(code,p1,p2);
	    default: return '';
	  }
	}
	function code4(code,p1,p2,p3){
	  switch(code){
	    case 'DD': return codeXD4(code,p1,p2,p3);
	    case 'ED': return codeXD4(code,p1,p2,p3);
	    case 'FD': return codeXD4(code,p1,p2,p3);
	    default:   return '';
	  }
	}
	function codeCB(code,p1){
	  if (code!='CB') return '';
	  switch(p1){
	    case '00': return rlc+'B';
	    case '01': return rlc+'C';
	    case '02': return rlc+'D';
	    case '03': return rlc+'E';
	    case '04': return rlc+'H';
	    case '05': return rlc+'L';
	    case '06': return rlc+'(HL)';
	    case '07': return rlc+'A';
	    case '08': return rrc+'B';
	    case '09': return rrc+'C';
	    case '0A': return rrc+'D';
	    case '0B': return rrc+'E';
	    case '0C': return rrc+'H';
	    case '0D': return rrc+'L';
	    case '0E': return rrc+'(HL)';
	    case '0F': return rrc+'A';
	    case '10': return rl+'B';
	    case '11': return rl+'C';
	    case '12': return rl+'D';
	    case '13': return rl+'E';
	    case '14': return rl+'H';
	    case '15': return rl+'L';
	    case '16': return rl+'(HL)';
	    case '17': return rl+'A';
	    case '18': return rr+'B';
	    case '19': return rr+'C';
	    case '1A': return rr+'D';
	    case '1B': return rr+'E';
	    case '1C': return rr+'H';
	    case '1D': return rr+'L';
	    case '1E': return rr+'(HL)';
	    case '1F': return rr+'A';
	    case '20': return sla+'B';
	    case '21': return sla+'C';
	    case '22': return sla+'D';
	    case '23': return sla+'E';
	    case '24': return sla+'H';
	    case '25': return sla+'L';
	    case '26': return sla+'(HL)';
	    case '27': return sla+'A';
	    case '28': return sra+'B';
	    case '29': return sra+'C';
	    case '2A': return sra+'D';
	    case '2B': return sra+'E';
	    case '2C': return sra+'H';
	    case '2D': return sra+'L';
	    case '2E': return sra+'(HL)';
	    case '2F': return sra+'A';
	    case '30': return sll+'B';
	    case '31': return sll+'C';
	    case '32': return sll+'D';
	    case '33': return sll+'E';
	    case '34': return sll+'H';
	    case '35': return sll+'L';
	    case '36': return sll+'(HL)';
	    case '37': return sll+'A';
	    case '38': return srl+'B';
	    case '39': return srl+'C';
	    case '3A': return srl+'D';
	    case '3B': return srl+'E';
	    case '3C': return srl+'H';
	    case '3D': return srl+'L';
	    case '3E': return srl+'(HL)';
	    case '3F': return srl+'A';
	    case '40': return bit+'0,B';
	    case '41': return bit+'0,C';
	    case '42': return bit+'0,D';
	    case '43': return bit+'0,E';
	    case '44': return bit+'0,H';
	    case '45': return bit+'0,L';
	    case '46': return bit+'0,(HL)';
	    case '47': return bit+'0,A';
	    case '48': return bit+'1,B';
	    case '49': return bit+'1,C';
	    case '4A': return bit+'1,D';
	    case '4B': return bit+'1,E';
	    case '4C': return bit+'1,H';
	    case '4D': return bit+'1,L';
	    case '4E': return bit+'1,(HL)';
	    case '4F': return bit+'1,A';
	    case '50': return bit+'2,B';
	    case '51': return bit+'2,C';
	    case '52': return bit+'2,D';
	    case '53': return bit+'2,E';
	    case '54': return bit+'2,H';
	    case '55': return bit+'2,L';
	    case '56': return bit+'2,(HL)';
	    case '57': return bit+'2,A';
	    case '58': return bit+'3,B';
	    case '59': return bit+'3,C';
	    case '5A': return bit+'3,D';
	    case '5B': return bit+'3,E';
	    case '5C': return bit+'3,H';
	    case '5D': return bit+'3,L';
	    case '5E': return bit+'3,(HL)';
	    case '5F': return bit+'3,A';
	    case '60': return bit+'4,B';
	    case '61': return bit+'4,C';
	    case '62': return bit+'4,D';
	    case '63': return bit+'4,E';
	    case '64': return bit+'4,H';
	    case '65': return bit+'4,L';
	    case '66': return bit+'4,(HL)';
	    case '67': return bit+'4,A';
	    case '68': return bit+'5,B';
	    case '69': return bit+'5,C';
	    case '6A': return bit+'5,D';
	    case '6B': return bit+'5,E';
	    case '6C': return bit+'5,H';
	    case '6D': return bit+'5,L';
	    case '6E': return bit+'5,(HL)';
	    case '6F': return bit+'5,A';
	    case '70': return bit+'6,B';
	    case '71': return bit+'6,C';
	    case '72': return bit+'6,D';
	    case '73': return bit+'6,E';
	    case '74': return bit+'6,H';
	    case '75': return bit+'6,L';
	    case '76': return bit+'6,(HL)';
	    case '77': return bit+'6,A';
	    case '78': return bit+'7,B';
	    case '79': return bit+'7,C';
	    case '7A': return bit+'7,D';
	    case '7B': return bit+'7,E';
	    case '7C': return bit+'7,H';
	    case '7D': return bit+'7,L';
	    case '7E': return bit+'7,(HL)';
	    case '7F': return bit+'7,A';
	    case '80': return res+'0,B';
	    case '81': return res+'0,C';
	    case '82': return res+'0,D';
	    case '83': return res+'0,E';
	    case '84': return res+'0,H';
	    case '85': return res+'0,L';
	    case '86': return res+'0,(HL)';
	    case '87': return res+'0,A';
	    case '88': return res+'1,B';
	    case '89': return res+'1,C';
	    case '8A': return res+'1,D';
	    case '8B': return res+'1,E';
	    case '8C': return res+'1,H';
	    case '8D': return res+'1,L';
	    case '8E': return res+'1,(HL)';
	    case '8F': return res+'1,A';
	    case '90': return res+'2,B';
	    case '91': return res+'2,C';
	    case '92': return res+'2,D';
	    case '93': return res+'2,E';
	    case '94': return res+'2,H';
	    case '95': return res+'2,L';
	    case '96': return res+'2,(HL)';
	    case '97': return res+'2,A';
	    case '98': return res+'3,B';
	    case '99': return res+'3,C';
	    case '9A': return res+'3,D';
	    case '9B': return res+'3,E';
	    case '9C': return res+'3,H';
	    case '9D': return res+'3,L';
	    case '9E': return res+'3,(HL)';
	    case '9F': return res+'3,A';
	    case 'A0': return res+'4,B';
	    case 'A1': return res+'4,C';
	    case 'A2': return res+'4,D';
	    case 'A3': return res+'4,E';
	    case 'A4': return res+'4,H';
	    case 'A5': return res+'4,L';
	    case 'A6': return res+'4,(HL)';
	    case 'A7': return res+'4,A';
	    case 'A8': return res+'5,B';
	    case 'A9': return res+'5,C';
	    case 'AA': return res+'5,D';
	    case 'AB': return res+'5,E';
	    case 'AC': return res+'5,H';
	    case 'AD': return res+'5,L';
	    case 'AE': return res+'5,(HL)';
	    case 'AF': return res+'5,A';
	    case 'B0': return res+'6,B';
	    case 'B1': return res+'6,C';
	    case 'B2': return res+'6,D';
	    case 'B3': return res+'6,E';
	    case 'B4': return res+'6,H';
	    case 'B5': return res+'6,L';
	    case 'B6': return res+'6,(HL)';
	    case 'B7': return res+'6,A';
	    case 'B8': return res+'7,B';
	    case 'B9': return res+'7,C';
	    case 'BA': return res+'7,D';
	    case 'BB': return res+'7,E';
	    case 'BC': return res+'7,H';
	    case 'BD': return res+'7,L';
	    case 'BE': return res+'7,(HL)';
	    case 'BF': return res+'7,A';
	    case 'C0': return set+'0,B';
	    case 'C1': return set+'0,C';
	    case 'C2': return set+'0,D';
	    case 'C3': return set+'0,E';
	    case 'C4': return set+'0,H';
	    case 'C5': return set+'0,L';
	    case 'C6': return set+'0,(HL)';
	    case 'C7': return set+'0,A';
	    case 'C8': return set+'1,B';
	    case 'C9': return set+'1,C';
	    case 'CA': return set+'1,D';
	    case 'CB': return set+'1,E';
	    case 'CC': return set+'1,H';
	    case 'CD': return set+'1,L';
	    case 'CE': return set+'1,(HL)';
	    case 'CF': return set+'1,A';
	    case 'D0': return set+'2,B';
	    case 'D1': return set+'2,C';
	    case 'D2': return set+'2,D';
	    case 'D3': return set+'2,E';
	    case 'D4': return set+'2,H';
	    case 'D5': return set+'2,L';
	    case 'D6': return set+'2,(HL)';
	    case 'D7': return set+'2,A';
	    case 'D8': return set+'3,B';
	    case 'D9': return set+'3,C';
	    case 'DA': return set+'3,D';
	    case 'DB': return set+'3,E';
	    case 'DC': return set+'3,H';
	    case 'DD': return set+'3,L';
	    case 'DE': return set+'3,(HL)';
	    case 'DF': return set+'3,A';
	    case 'E0': return set+'4,B';
	    case 'E1': return set+'4,C';
	    case 'E2': return set+'4,D';
	    case 'E3': return set+'4,E';
	    case 'E4': return set+'4,H';
	    case 'E5': return set+'4,L';
	    case 'E6': return set+'4,(HL)';
	    case 'E7': return set+'4,A';
	    case 'E8': return set+'5,B';
	    case 'E9': return set+'5,C';
	    case 'EA': return set+'5,D';
	    case 'EB': return set+'5,E';
	    case 'EC': return set+'5,H';
	    case 'ED': return set+'5,L';
	    case 'EE': return set+'5,(HL)';
	    case 'EF': return set+'5,A';
	    case 'F0': return set+'6,B';
	    case 'F1': return set+'6,C';
	    case 'F2': return set+'6,D';
	    case 'F3': return set+'6,E';
	    case 'F4': return set+'6,H';
	    case 'F5': return set+'6,L';
	    case 'F6': return set+'6,(HL)';
	    case 'F7': return set+'6,A';
	    case 'F8': return set+'7,B';
	    case 'F9': return set+'7,C';
	    case 'FA': return set+'7,D';
	    case 'FB': return set+'7,E';
	    case 'FC': return set+'7,H';
	    case 'FD': return set+'7,L';
	    case 'FE': return set+'7,(HL)';
	    case 'FF': return set+'7,A';
	    default: return '';
	  }
	}
	function codeED(code,p1){
	  switch(code+p1){

	    case 'ED40': return 'IN    B,(C)';
	    case 'ED41': return 'OUT   (C),B';
	    case 'ED42': return 'SBC   HL,BC';
	    case 'ED44': return 'NEG';
	    case 'ED45': return 'RETN';
	    case 'ED46': return 'IM    0';
	    case 'ED47': return ld+'I,A';
	    case 'ED48': return 'IN    C,(C)';
	    case 'ED49': return 'OUT   (C),C';
	    case 'ED4A': return 'ADC   HL,BC';
	    case 'ED4C': return 'NEG*';
	    case 'ED4D': return 'RETI';
	    case 'ED4E': return 'IM    0*';
	    case 'ED4F': return ld+'R,A';
	    case 'ED50': return 'IN    D,(C)';
	    case 'ED51': return 'OUT   (C),D';
	    case 'ED52': return 'SBC   HL,DE';
	    case 'ED54': return 'NEG*';
	    case 'ED55': return 'RETN*';
	    case 'ED56': return 'IM    1';
	    case 'ED57': return ld+'A,I';
	    case 'ED58': return 'IN    E,(C)';
	    case 'ED59': return 'OUT   (C),E';
	    case 'ED5A': return 'ADC   HL,DE';
	    case 'ED5C': return 'NEG*';
	    case 'ED5D': return 'RETN*';
	    case 'ED5E': return 'IM    2';
	    case 'ED5F': return ld+'A,R';
	    case 'ED60': return 'IN    H,(C)';
	    case 'ED61': return 'OUT   (C),H';
	    case 'ED62': return 'SBC   HL,HL';
	    case 'ED64': return 'NEG*';
	    case 'ED65': return 'RETN*';
	    case 'ED66': return 'IM    0*';
	    case 'ED67': return 'RRD';
	    case 'ED68': return 'IN    L,(C)';
	    case 'ED69': return 'OUT   (C),L';
	    case 'ED6A': return 'ADC   HL,HL';
	    case 'ED6C': return 'NEG*';
	    case 'ED6D': return 'RETN*';
	    case 'ED6E': return 'IM    0*';
	    case 'ED6F': return 'RLD';
	    case 'ED70': return 'IN    F,(C)';
	    case 'ED71': return 'OUT   (C),0';
	    case 'ED72': return 'SBC   HL,SP';
	    case 'ED74': return 'NEG*';
	    case 'ED75': return 'RETN*';
	    case 'ED76': return 'IM    1*';
	    case 'ED77': return 'NOP*';
	    case 'ED78': return 'IN    A,(C)';
	    case 'ED79': return 'OUT   (c),A';
	    case 'ED7A': return 'ADC   HL,SP';
	    case 'ED7C': return 'NEG*';
	    case 'ED7D': return 'RETN*';
	    case 'ED7E': return 'IM    2*';
	    case 'ED7F': return 'NOP*';
	    case 'EDA0': return 'LDI';
	    case 'EDA1': return 'CPI';
	    case 'EDA2': return 'INI';
	    case 'EDA3': return 'OUTI';
	    case 'EDA8': return 'LDD';
	    case 'EDA9': return 'CPD';
	    case 'EDAA': return 'IND';
	    case 'EDAB': return 'OUTD';
	    case 'EDB0': return 'LDIR';
	    case 'EDB1': return 'CPIR';
	    case 'EDB2': return 'INIR';
	    case 'EDB3': return 'OTIR';
	    case 'EDB8': return 'LDDR';
	    case 'EDB9': return 'CPDR';
	    case 'EDBA': return 'INDR';
	    case 'EDBB': return 'OTDR';
	    default:     return '';
	  }
	};

	function codeXD2(code,p1){
	  switch(code+p1){

	    case 'DD09': return 'ADD   IX,BC';
	    case 'DD19': return 'ADD   IX,DE';
	    case 'DD23': return 'INC   IX';
	    case 'DD24': return 'INC   IXH';
	    case 'DD25': return 'DEC   IXH';
	    case 'DD29': return 'ADD   IX,IX';
	    case 'DD2B': return 'DEC   IX';
	    case 'DD2C': return 'INC   IXL';
	    case 'DD2D': return 'DEC   IXL';
	    case 'DD39': return 'ADD   IX,SP';
	    case 'DD44': return ld+'B,IXH';
	    case 'DD45': return ld+'B,IXL';
	    case 'DD4C': return ld+'C,IXH';
	    case 'DD4D': return ld+'C,IXL';
	    case 'DD54': return ld+'D,IXH';
	    case 'DD55': return ld+'D,IXL';
	    case 'DD5C': return ld+'E,IXH';
	    case 'DD5D': return ld+'E,IXL';
	    case 'DD60': return ld+'IXH,B';
	    case 'DD61': return ld+'IXH,C';
	    case 'DD62': return ld+'IXH,D';
	    case 'DD63': return ld+'IXH,E';
	    case 'DD64': return ld+'IXH,IXH';
	    case 'DD65': return ld+'IXH,IXL';
	    case 'DD67': return ld+'IXH,A';
	    case 'DD68': return ld+'IXL,B';
	    case 'DD69': return ld+'IXL,C';
	    case 'DD6A': return ld+'IXL,D';
	    case 'DD6B': return ld+'IXL,E';
	    case 'DD6C': return ld+'IXL,IXH';
	    case 'DD6D': return ld+'IXL,IXL';
	    case 'DD6F': return ld+'IXL,A';
	    case 'DD7C': return ld+'A,IXH';
	    case 'DD7D': return ld+'A,IXL';
	    case 'DD84': return 'ADD   A,IXH';
	    case 'DD85': return 'ADD   A,IXL';
	    case 'DD8C': return 'ADC   A,IXH';
	    case 'DD8D': return 'ADC   A,IXL';
	    case 'DD94': return 'SUB   IXH';
	    case 'DD95': return 'SUB   IXL';
	    case 'DD9C': return 'SBC   A,IXH';
	    case 'DD9D': return 'SBC   A,IXL';
	    case 'DDA4': return 'AND   IXH';
	    case 'DDA5': return 'AND   IXL';
	    case 'DDAC': return 'XOR   IXH';
	    case 'DDAD': return 'XOR   IXL';
	    case 'DDB4': return 'OR    IXH';
	    case 'DDB5': return 'OR    IXL';
	    case 'DDBC': return 'CP    IXH';
	    case 'DDBD': return 'CP    IXL';
	    case 'DDE1': return 'POP   IX';
	    case 'DDE3': return 'EX    (SP),IX';
	    case 'DDE5': return 'PUSH   IX';
	    case 'DDE9': return 'JP    (IX)';
	    case 'DDEB': return 'EX    DE,IX';
	    case 'DDF9': return ld+'SP,IX';

	    case 'FD09': return 'ADD   IY,BC';
	    case 'FD19': return 'ADD   IY,DE';
	    case 'FD23': return 'INC   IY';
	    case 'FD24': return 'INC   IYH';
	    case 'FD25': return 'DEC   IYH';
	    case 'FD29': return 'ADD   IY,IY';
	    case 'FD2B': return 'DEC   IY';
	    case 'FD2C': return 'INC   IYL';
	    case 'FD2D': return 'DEC   IYL';
	    case 'FD39': return 'ADD   IY,SP';
	    case 'FD44': return ld+'B,IYH';
	    case 'FD45': return ld+'B,IYL';
	    case 'FD4C': return ld+'C,IYH';
	    case 'FD4D': return ld+'C,IYL';
	    case 'FD54': return ld+'D,IYH';
	    case 'FD55': return ld+'D,IYL';
	    case 'FD5C': return ld+'E,IYH';
	    case 'FD5D': return ld+'E,IYL';
	    case 'FD60': return ld+'IYH,B';
	    case 'FD61': return ld+'IYH,C';
	    case 'FD62': return ld+'IYH,D';
	    case 'FD63': return ld+'IYH,E';
	    case 'FD64': return ld+'IYH,IYH';
	    case 'FD65': return ld+'IYH,IYL';
	    case 'FD67': return ld+'IYH,A';
	    case 'FD68': return ld+'IYL,B';
	    case 'FD69': return ld+'IYL,C';
	    case 'FD6A': return ld+'IYL,D';
	    case 'FD6B': return ld+'IYL,E';
	    case 'FD6C': return ld+'IYL,IYH';
	    case 'FD6D': return ld+'IYL,IYL';
	    case 'FD6F': return ld+'IYL,A';
	    case 'FD7C': return ld+'A,IYH';
	    case 'FD7D': return ld+'A,IYL';
	    case 'FD84': return 'ADD   A,IYH';
	    case 'FD85': return 'ADD   A,IYL';
	    case 'FD8C': return 'ADC   A,IYH';
	    case 'FD8D': return 'ADC   A,IYL';
	    case 'FD94': return 'SUB   IYH';
	    case 'FD95': return 'SUB   IYL';
	    case 'FD9C': return 'SBC   A,IYH';
	    case 'FD9D': return 'SBC   A,IYL';
	    case 'FDA4': return 'AND   IYH';
	    case 'FDA5': return 'AND   IYL';
	    case 'FDAC': return 'XOR   IYH';
	    case 'FDAD': return 'XOR   IYL';
	    case 'FDB4': return 'OR    IYH';
	    case 'FDB5': return 'OR    IYL';
	    case 'FDBC': return 'CP    IYH';
	    case 'FDBD': return 'CP    IYL';
	    case 'FDE1': return 'POP   IY';
	    case 'FDE3': return 'EX    (SP),IY';
	    case 'FDE5': return 'PUSH   IY';
	    case 'FDE9': return 'JP    (IY)';
	    case 'FDEB': return 'EX    DE,IY';
	    case 'FDF9': return ld+'SP,IY';

	    default:     return '';
	  }
	}
	function codeXD3(code,p1,p2){
	  switch(code+p1){
	    case 'DD34': return 'INC   (IX+'+p2+')';
	    case 'DD35': return 'DEC   (IX+'+p2+')';
	    case 'DD46': return ld+'B,(IX+'+p2+')';
	    case 'DD4E': return ld+'C,(IX+'+p2+')';
	    case 'DD56': return ld+'D,(IX+'+p2+')';
	    case 'DD5E': return ld+'E,(IX+'+p2+')';
	    case 'DD66': return ld+'H,(IX+'+p2+')';
	    case 'DD6E': return ld+'L,(IX+'+p2+')';
	    case 'DD70': return ld+'(IX+'+p2+'),B';
	    case 'DD71': return ld+'(IX+'+p2+'),C';
	    case 'DD72': return ld+'(IX+'+p2+'),D';
	    case 'DD73': return ld+'(IX+'+p2+'),E';
	    case 'DD74': return ld+'(IX+'+p2+'),H';
	    case 'DD75': return ld+'(IX+'+p2+'),L';
	    case 'DD77': return ld+'(IX+'+p2+'),A';
	    case 'DD7E': return ld+'A,(IX+'+p2+')';
	    case 'DD86': return 'ADD   A,(IX+'+p2+')';
	    case 'DD8E': return 'ADC   A,(IX+'+p2+')';
	    case 'DD96': return 'SUB   A,(IX+'+p2+')';
	    case 'DD9E': return 'SBC   A,(IX+'+p2+')';
	    case 'DDA6': return 'AND   (IX+'+p2+')';
	    case 'DDAE': return 'XOR   (IX+'+p2+')';
	    case 'DDB6': return 'OR    (IX+'+p2+')';
	    case 'DDBE': return 'CP    (IX+'+p2+')';
	    case 'FD34': return 'INC   (IY+'+p2+')';
	    case 'FD35': return 'DEC   (IY+'+p2+')';
	    case 'FD46': return ld+'B,(IY+'+p2+')';
	    case 'FD4E': return ld+'C,(IY+'+p2+')';
	    case 'FD56': return ld+'D,(IY+'+p2+')';
	    case 'FD5E': return ld+'E,(IY+'+p2+')';
	    case 'FD66': return ld+'H,(IY+'+p2+')';
	    case 'FD6E': return ld+'L,(IY+'+p2+')';
	    case 'FD70': return ld+'(IY+'+p2+'),B';
	    case 'FD71': return ld+'(IY+'+p2+'),C';
	    case 'FD72': return ld+'(IY+'+p2+'),D';
	    case 'FD73': return ld+'(IY+'+p2+'),E';
	    case 'FD74': return ld+'(IY+'+p2+'),H';
	    case 'FD75': return ld+'(IY+'+p2+'),L';
	    case 'FD77': return ld+'(IY+'+p2+'),A';
	    case 'FD7E': return ld+'A,(IY+'+p2+')';
	    case 'FD86': return 'ADD   A,(IY+'+p2+')';
	    case 'FD8E': return 'ADC   A,(IY+'+p2+')';
	    case 'FD96': return 'SUB   A,(IY+'+p2+')';
	    case 'FD9E': return 'SBC   A,(IY+'+p2+')';
	    case 'FDA6': return 'AND   (IY+'+p2+')';
	    case 'FDAE': return 'XOR   (IY+'+p2+')';
	    case 'FDB6': return 'OR    (IY+'+p2+')';
	    case 'FDBE': return 'CP    (IY+'+p2+')';
	    default:     return '';
	  }
	}
	function codeXD4(code,p1,p2,p3){
		var p3p2 = p3+p2;
	  switch(code+p1){
	    case 'DD21': return ld+'IX,'+p3p2;
	    case 'DD22': return ld+'('+p3p2+'),IX';
	    case 'DD2A': return ld+'IX,('+p3p2+')';
	    case 'DD36': return ld+'(IX+'+p2+'),'+p3;
	    case 'ED43': return ld+'('+p3p2+'),BC';
	    case 'ED4B': return ld+'BC,('+p3p2+')';
	    case 'ED53': return ld+'('+p3p2+'),DE';
	    case 'ED5B': return ld+'DE,('+p3p2+')';
	    case 'ED73': return ld+'('+p3p2+'),SP';
	    case 'ED7B': return ld+'SP,('+p3p2+')';
	    case 'FD21': return ld+'IY,'+p3p2;
	    case 'FD22': return ld+'('+p3p2+'),IY';
	    case 'FD2A': return ld+'IY,('+p3p2+')';
	    case 'FD36': return ld+'(IY+'+p2+'),'+p3;
	    default:     break;
	  }
	  switch(code+p1+p3){
	  	case 'DDCB00': return rlc+'(IX+'+p2+'),B';
	  	case 'DDCB01': return rlc+'(IX+'+p2+'),C';
	  	case 'DDCB02': return rlc+'(IX+'+p2+'),D';
	  	case 'DDCB03': return rlc+'(IX+'+p2+'),E';
	  	case 'DDCB04': return rlc+'(IX+'+p2+'),H';
	  	case 'DDCB05': return rlc+'(IX+'+p2+'),L';
	  	case 'DDCB06': return rlc+'(IX+'+p2+')';
	  	case 'DDCB07': return rlc+'(IX+'+p2+'),A';
	  	case 'DDCB08': return rrc+'(IX+'+p2+'),B';
	  	case 'DDCB09': return rrc+'(IX+'+p2+'),C';
	  	case 'DDCB0A': return rrc+'(IX+'+p2+'),D';
	  	case 'DDCB0B': return rrc+'(IX+'+p2+'),E';
	  	case 'DDCB0C': return rrc+'(IX+'+p2+'),H';
	  	case 'DDCB0D': return rrc+'(IX+'+p2+'),L';
	  	case 'DDCB0E': return rrc+'(IX+'+p2+')';
	  	case 'DDCB0F': return rrc+'(IX+'+p2+'),A';
	  	case 'DDCB10': return rl+'(IX+'+p2+'),B';
	  	case 'DDCB11': return rl+'(IX+'+p2+'),C';
	  	case 'DDCB12': return rl+'(IX+'+p2+'),D';
	  	case 'DDCB13': return rl+'(IX+'+p2+'),E';
	  	case 'DDCB14': return rl+'(IX+'+p2+'),H';
	  	case 'DDCB15': return rl+'(IX+'+p2+'),L';
	  	case 'DDCB16': return rl+'(IX+'+p2+')';
	  	case 'DDCB17': return rl+'(IX+'+p2+'),A';
	  	case 'DDCB18': return rr+'(IX+'+p2+'),B';
	  	case 'DDCB19': return rr+'(IX+'+p2+'),C';
	  	case 'DDCB1A': return rr+'(IX+'+p2+'),D';
	  	case 'DDCB1B': return rr+'(IX+'+p2+'),E';
	  	case 'DDCB1C': return rr+'(IX+'+p2+'),H';
	  	case 'DDCB1D': return rr+'(IX+'+p2+'),L';
	  	case 'DDCB1E': return rr+'(IX+'+p2+')';
	  	case 'DDCB1F': return rr+'(IX+'+p2+'),A';
	  	case 'DDCB20': return sla+'(IX+'+p2+'),B';
	  	case 'DDCB21': return sla+'(IX+'+p2+'),C';
	  	case 'DDCB22': return sla+'(IX+'+p2+'),D';
	  	case 'DDCB23': return sla+'(IX+'+p2+'),E';
	  	case 'DDCB24': return sla+'(IX+'+p2+'),H';
	  	case 'DDCB25': return sla+'(IX+'+p2+'),L';
	  	case 'DDCB26': return sla+'(IX+'+p2+')';
	  	case 'DDCB27': return sla+'(IX+'+p2+'),A';
	  	case 'DDCB28': return sra+'(IX+'+p2+'),B';
	  	case 'DDCB29': return sra+'(IX+'+p2+'),C';
	  	case 'DDCB2A': return sra+'(IX+'+p2+'),D';
	  	case 'DDCB2B': return sra+'(IX+'+p2+'),E';
	  	case 'DDCB2C': return sra+'(IX+'+p2+'),H';
	  	case 'DDCB2D': return sra+'(IX+'+p2+'),L';
	  	case 'DDCB2E': return sra+'(IX+'+p2+')';
	  	case 'DDCB2F': return sra+'(IX+'+p2+'),A';
	  	case 'DDCB30': return sll+'(IX+'+p2+'),B';
	  	case 'DDCB31': return sll+'(IX+'+p2+'),C';
	  	case 'DDCB32': return sll+'(IX+'+p2+'),D';
	  	case 'DDCB33': return sll+'(IX+'+p2+'),E';
	  	case 'DDCB34': return sll+'(IX+'+p2+'),H';
	  	case 'DDCB35': return sll+'(IX+'+p2+'),L';
	  	case 'DDCB36': return sll+'(IX+'+p2+')';
	  	case 'DDCB37': return sll+'(IX+'+p2+'),A';
	  	case 'DDCB38': return srl+'(IX+'+p2+'),B';
	  	case 'DDCB39': return srl+'(IX+'+p2+'),C';
	  	case 'DDCB3A': return srl+'(IX+'+p2+'),D';
	  	case 'DDCB3B': return srl+'(IX+'+p2+'),E';
	  	case 'DDCB3C': return srl+'(IX+'+p2+'),H';
	  	case 'DDCB3D': return srl+'(IX+'+p2+'),L';
	  	case 'DDCB3E': return srl+'(IX+'+p2+')';
	  	case 'DDCB3F': return srl+'(IX+'+p2+'),A';
	  	case 'DDCB40': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB41': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB42': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB43': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB44': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB45': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB46': return bit+'0,(IX+'+p2+')';
	  	case 'DDCB47': return bit+'0,(IX+'+p2+')*';
	  	case 'DDCB48': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB49': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB4A': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB4B': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB4C': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB4D': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB4E': return bit+'1,(IX+'+p2+')';
	  	case 'DDCB4F': return bit+'1,(IX+'+p2+')*';
	  	case 'DDCB50': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB51': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB52': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB53': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB54': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB55': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB56': return bit+'2,(IX+'+p2+')';
	  	case 'DDCB57': return bit+'2,(IX+'+p2+')*';
	  	case 'DDCB58': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB59': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB5A': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB5B': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB5C': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB5D': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB5E': return bit+'3,(IX+'+p2+')';
	  	case 'DDCB5F': return bit+'3,(IX+'+p2+')*';
	  	case 'DDCB60': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB61': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB62': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB63': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB64': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB65': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB66': return bit+'4,(IX+'+p2+')';
	  	case 'DDCB67': return bit+'4,(IX+'+p2+')*';
	  	case 'DDCB68': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB69': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB6A': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB6B': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB6C': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB6D': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB6E': return bit+'5,(IX+'+p2+')';
	  	case 'DDCB6F': return bit+'5,(IX+'+p2+')*';
	  	case 'DDCB70': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB71': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB72': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB73': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB74': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB75': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB76': return bit+'6,(IX+'+p2+')';
	  	case 'DDCB77': return bit+'6,(IX+'+p2+')*';
	  	case 'DDCB78': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB79': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB7A': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB7B': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB7C': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB7D': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB7E': return bit+'7,(IX+'+p2+')';
	  	case 'DDCB7F': return bit+'7,(IX+'+p2+')*';
	  	case 'DDCB80': return res+'0,(IX+'+p2+'),B';
	  	case 'DDCB81': return res+'0,(IX+'+p2+'),C';
	  	case 'DDCB82': return res+'0,(IX+'+p2+'),D';
	  	case 'DDCB83': return res+'0,(IX+'+p2+'),E';
	  	case 'DDCB84': return res+'0,(IX+'+p2+'),H';
	  	case 'DDCB85': return res+'0,(IX+'+p2+'),L';
	  	case 'DDCB86': return res+'0,(IX+'+p2+')';
	  	case 'DDCB87': return res+'0,(IX+'+p2+'),A';
	  	case 'DDCB88': return res+'1,(IX+'+p2+'),B';
	  	case 'DDCB89': return res+'1,(IX+'+p2+'),C';
	  	case 'DDCB8A': return res+'1,(IX+'+p2+'),D';
	  	case 'DDCB8B': return res+'1,(IX+'+p2+'),E';
	  	case 'DDCB8C': return res+'1,(IX+'+p2+'),H';
	  	case 'DDCB8D': return res+'1,(IX+'+p2+'),L';
	  	case 'DDCB8E': return res+'1,(IX+'+p2+')';
	  	case 'DDCB8F': return res+'1,(IX+'+p2+'),A';
	  	case 'DDCB90': return res+'2,(IX+'+p2+'),B';
	  	case 'DDCB91': return res+'2,(IX+'+p2+'),C';
	  	case 'DDCB92': return res+'2,(IX+'+p2+'),D';
	  	case 'DDCB93': return res+'2,(IX+'+p2+'),E';
	  	case 'DDCB94': return res+'2,(IX+'+p2+'),H';
	  	case 'DDCB95': return res+'2,(IX+'+p2+'),L';
	  	case 'DDCB96': return res+'2,(IX+'+p2+')';
	  	case 'DDCB97': return res+'2,(IX+'+p2+'),A';
	  	case 'DDCB98': return res+'3,(IX+'+p2+'),B';
	  	case 'DDCB99': return res+'3,(IX+'+p2+'),C';
	  	case 'DDCB9A': return res+'3,(IX+'+p2+'),D';
	  	case 'DDCB9B': return res+'3,(IX+'+p2+'),E';
	  	case 'DDCB9C': return res+'3,(IX+'+p2+'),H';
	  	case 'DDCB9D': return res+'3,(IX+'+p2+'),L';
	  	case 'DDCB9E': return res+'3,(IX+'+p2+')';
	  	case 'DDCB9F': return res+'3,(IX+'+p2+'),A';
	  	case 'DDCBA0': return res+'4,(IX+'+p2+'),B';
	  	case 'DDCBA1': return res+'4,(IX+'+p2+'),C';
	  	case 'DDCBA2': return res+'4,(IX+'+p2+'),D';
	  	case 'DDCBA3': return res+'4,(IX+'+p2+'),E';
	  	case 'DDCBA4': return res+'4,(IX+'+p2+'),H';
	  	case 'DDCBA5': return res+'4,(IX+'+p2+'),L';
	  	case 'DDCBA6': return res+'4,(IX+'+p2+')';
	  	case 'DDCBA7': return res+'4,(IX+'+p2+'),A';
	  	case 'DDCBA8': return res+'5,(IX+'+p2+'),B';
	  	case 'DDCBA9': return res+'5,(IX+'+p2+'),C';
	  	case 'DDCBAA': return res+'5,(IX+'+p2+'),D';
	  	case 'DDCBAB': return res+'5,(IX+'+p2+'),E';
	  	case 'DDCBAC': return res+'5,(IX+'+p2+'),H';
	  	case 'DDCBAD': return res+'5,(IX+'+p2+'),L';
	  	case 'DDCBAE': return res+'5,(IX+'+p2+')';
	  	case 'DDCBAF': return res+'5,(IX+'+p2+'),A';
	  	case 'DDCBB0': return res+'6,(IX+'+p2+'),B';
	  	case 'DDCBB1': return res+'6,(IX+'+p2+'),C';
	  	case 'DDCBB2': return res+'6,(IX+'+p2+'),D';
	  	case 'DDCBB3': return res+'6,(IX+'+p2+'),E';
	  	case 'DDCBB4': return res+'6,(IX+'+p2+'),H';
	  	case 'DDCBB5': return res+'6,(IX+'+p2+'),L';
	  	case 'DDCBB6': return res+'6,(IX+'+p2+')';
	  	case 'DDCBB7': return res+'6,(IX+'+p2+'),A';
	  	case 'DDCBB8': return res+'7,(IX+'+p2+'),B';
	  	case 'DDCBB9': return res+'7,(IX+'+p2+'),C';
	  	case 'DDCBBA': return res+'7,(IX+'+p2+'),D';
	  	case 'DDCBBB': return res+'7,(IX+'+p2+'),E';
	  	case 'DDCBBC': return res+'7,(IX+'+p2+'),H';
	  	case 'DDCBBD': return res+'7,(IX+'+p2+'),L';
	  	case 'DDCBBE': return res+'7,(IX+'+p2+')';
	  	case 'DDCBBF': return res+'7,(IX+'+p2+'),A';
	  	case 'DDCBC0': return set+'0,(IX+'+p2+'),B';
	  	case 'DDCBC1': return set+'0,(IX+'+p2+'),C';
	  	case 'DDCBC2': return set+'0,(IX+'+p2+'),D';
	  	case 'DDCBC3': return set+'0,(IX+'+p2+'),E';
	  	case 'DDCBC4': return set+'0,(IX+'+p2+'),H';
	  	case 'DDCBC5': return set+'0,(IX+'+p2+'),L';
	  	case 'DDCBC6': return set+'0,(IX+'+p2+')';
	  	case 'DDCBC7': return set+'0,(IX+'+p2+'),A';
	  	case 'DDCBC8': return set+'1,(IX+'+p2+'),B';
	  	case 'DDCBC9': return set+'1,(IX+'+p2+'),C';
	  	case 'DDCBCA': return set+'1,(IX+'+p2+'),D';
	  	case 'DDCBCB': return set+'1,(IX+'+p2+'),E';
	  	case 'DDCBCC': return set+'1,(IX+'+p2+'),H';
	  	case 'DDCBCD': return set+'1,(IX+'+p2+'),L';
	  	case 'DDCBCE': return set+'1,(IX+'+p2+')';
	  	case 'DDCBCF': return set+'1,(IX+'+p2+'),A';
	  	case 'DDCBD0': return set+'2,(IX+'+p2+'),B';
	  	case 'DDCBD1': return set+'2,(IX+'+p2+'),C';
	  	case 'DDCBD2': return set+'2,(IX+'+p2+'),D';
	  	case 'DDCBD3': return set+'2,(IX+'+p2+'),E';
	  	case 'DDCBD4': return set+'2,(IX+'+p2+'),H';
	  	case 'DDCBD5': return set+'2,(IX+'+p2+'),L';
	  	case 'DDCBD6': return set+'2,(IX+'+p2+')';
	  	case 'DDCBD7': return set+'2,(IX+'+p2+'),A';
	  	case 'DDCBD8': return set+'3,(IX+'+p2+'),B';
	  	case 'DDCBD9': return set+'3,(IX+'+p2+'),C';
	  	case 'DDCBDA': return set+'3,(IX+'+p2+'),D';
	  	case 'DDCBDB': return set+'3,(IX+'+p2+'),E';
	  	case 'DDCBDC': return set+'3,(IX+'+p2+'),H';
	  	case 'DDCBDD': return set+'3,(IX+'+p2+'),L';
	  	case 'DDCBDE': return set+'3,(IX+'+p2+')';
	  	case 'DDCBDF': return set+'3,(IX+'+p2+'),A';
	  	case 'DDCBE0': return set+'4,(IX+'+p2+'),B';
	  	case 'DDCBE1': return set+'4,(IX+'+p2+'),C';
	  	case 'DDCBE2': return set+'4,(IX+'+p2+'),D';
	  	case 'DDCBE3': return set+'4,(IX+'+p2+'),E';
	  	case 'DDCBE4': return set+'4,(IX+'+p2+'),H';
	  	case 'DDCBE5': return set+'4,(IX+'+p2+'),L';
	  	case 'DDCBE6': return set+'4,(IX+'+p2+')';
	  	case 'DDCBE7': return set+'4,(IX+'+p2+'),A';
	  	case 'DDCBE8': return set+'5,(IX+'+p2+'),B';
	  	case 'DDCBE9': return set+'5,(IX+'+p2+'),C';
	  	case 'DDCBEA': return set+'5,(IX+'+p2+'),D';
	  	case 'DDCBEB': return set+'5,(IX+'+p2+'),E';
	  	case 'DDCBEC': return set+'5,(IX+'+p2+'),H';
	  	case 'DDCBED': return set+'5,(IX+'+p2+'),L';
	  	case 'DDCBEE': return set+'5,(IX+'+p2+')';
	  	case 'DDCBEF': return set+'5,(IX+'+p2+'),A';
	  	case 'DDCBF0': return set+'6,(IX+'+p2+'),B';
	  	case 'DDCBF1': return set+'6,(IX+'+p2+'),C';
	  	case 'DDCBF2': return set+'6,(IX+'+p2+'),D';
	  	case 'DDCBF3': return set+'6,(IX+'+p2+'),E';
	  	case 'DDCBF4': return set+'6,(IX+'+p2+'),H';
	  	case 'DDCBF5': return set+'6,(IX+'+p2+'),L';
	  	case 'DDCBF6': return set+'6,(IX+'+p2+')';
	  	case 'DDCBF7': return set+'6,(IX+'+p2+'),A';
	  	case 'DDCBF8': return set+'7,(IX+'+p2+'),B';
	  	case 'DDCBF9': return set+'7,(IX+'+p2+'),C';
	  	case 'DDCBFA': return set+'7,(IX+'+p2+'),D';
	  	case 'DDCBFB': return set+'7,(IX+'+p2+'),E';
	  	case 'DDCBFC': return set+'7,(IX+'+p2+'),H';
	  	case 'DDCBFD': return set+'7,(IX+'+p2+'),L';
	  	case 'DDCBFE': return set+'7,(IX+'+p2+')';
	  	case 'DDCBFF': return set+'7,(IX+'+p2+'),A';
	  	case 'FDCB00': return rlc+'(IY+'+p2+'),B';
	  	case 'FDCB01': return rlc+'(IY+'+p2+'),C';
	  	case 'FDCB02': return rlc+'(IY+'+p2+'),D';
	  	case 'FDCB03': return rlc+'(IY+'+p2+'),E';
	  	case 'FDCB04': return rlc+'(IY+'+p2+'),H';
	  	case 'FDCB05': return rlc+'(IY+'+p2+'),L';
	  	case 'FDCB06': return rlc+'(IY+'+p2+')';
	  	case 'FDCB07': return rlc+'(IY+'+p2+'),A';
	  	case 'FDCB08': return rrc+'(IY+'+p2+'),B';
	  	case 'FDCB09': return rrc+'(IY+'+p2+'),C';
	  	case 'FDCB0A': return rrc+'(IY+'+p2+'),D';
	  	case 'FDCB0B': return rrc+'(IY+'+p2+'),E';
	  	case 'FDCB0C': return rrc+'(IY+'+p2+'),H';
	  	case 'FDCB0D': return rrc+'(IY+'+p2+'),L';
	  	case 'FDCB0E': return rrc+'(IY+'+p2+')';
	  	case 'FDCB0F': return rrc+'(IY+'+p2+'),A';
	  	case 'FDCB10': return rl+'(IY+'+p2+'),B';
	  	case 'FDCB11': return rl+'(IY+'+p2+'),C';
	  	case 'FDCB12': return rl+'(IY+'+p2+'),D';
	  	case 'FDCB13': return rl+'(IY+'+p2+'),E';
	  	case 'FDCB14': return rl+'(IY+'+p2+'),H';
	  	case 'FDCB15': return rl+'(IY+'+p2+'),L';
	  	case 'FDCB16': return rl+'(IY+'+p2+')';
	  	case 'FDCB17': return rl+'(IY+'+p2+'),A';
	  	case 'FDCB18': return rr+'(IY+'+p2+'),B';
	  	case 'FDCB19': return rr+'(IY+'+p2+'),C';
	  	case 'FDCB1A': return rr+'(IY+'+p2+'),D';
	  	case 'FDCB1B': return rr+'(IY+'+p2+'),E';
	  	case 'FDCB1C': return rr+'(IY+'+p2+'),H';
	  	case 'FDCB1D': return rr+'(IY+'+p2+'),L';
	  	case 'FDCB1E': return rr+'(IY+'+p2+')';
	  	case 'FDCB1F': return rr+'(IY+'+p2+'),A';
	  	case 'FDCB20': return sla+'(IY+'+p2+'),B';
	  	case 'FDCB21': return sla+'(IY+'+p2+'),C';
	  	case 'FDCB22': return sla+'(IY+'+p2+'),D';
	  	case 'FDCB23': return sla+'(IY+'+p2+'),E';
	  	case 'FDCB24': return sla+'(IY+'+p2+'),H';
	  	case 'FDCB25': return sla+'(IY+'+p2+'),L';
	  	case 'FDCB26': return sla+'(IY+'+p2+')';
	  	case 'FDCB27': return sla+'(IY+'+p2+'),A';
	  	case 'FDCB28': return sra+'(IY+'+p2+'),B';
	  	case 'FDCB29': return sra+'(IY+'+p2+'),C';
	  	case 'FDCB2A': return sra+'(IY+'+p2+'),D';
	  	case 'FDCB2B': return sra+'(IY+'+p2+'),E';
	  	case 'FDCB2C': return sra+'(IY+'+p2+'),H';
	  	case 'FDCB2D': return sra+'(IY+'+p2+'),L';
	  	case 'FDCB2E': return sra+'(IY+'+p2+')';
	  	case 'FDCB2F': return sra+'(IY+'+p2+'),A';
	  	case 'FDCB30': return sll+'(IY+'+p2+'),B';
	  	case 'FDCB31': return sll+'(IY+'+p2+'),C';
	  	case 'FDCB32': return sll+'(IY+'+p2+'),D';
	  	case 'FDCB33': return sll+'(IY+'+p2+'),E';
	  	case 'FDCB34': return sll+'(IY+'+p2+'),H';
	  	case 'FDCB35': return sll+'(IY+'+p2+'),L';
	  	case 'FDCB36': return sll+'(IY+'+p2+')';
	  	case 'FDCB37': return sll+'(IY+'+p2+'),A';
	  	case 'FDCB38': return srl+'(IY+'+p2+'),B';
	  	case 'FDCB39': return srl+'(IY+'+p2+'),C';
	  	case 'FDCB3A': return srl+'(IY+'+p2+'),D';
	  	case 'FDCB3B': return srl+'(IY+'+p2+'),E';
	  	case 'FDCB3C': return srl+'(IY+'+p2+'),H';
	  	case 'FDCB3D': return srl+'(IY+'+p2+'),L';
	  	case 'FDCB3E': return srl+'(IY+'+p2+')';
	  	case 'FDCB3F': return srl+'(IY+'+p2+'),A';
	  	case 'FDCB40': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB41': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB42': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB43': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB44': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB45': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB46': return bit+'0,(IY+'+p2+')';
	  	case 'FDCB47': return bit+'0,(IY+'+p2+')*';
	  	case 'FDCB48': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB49': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB4A': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB4B': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB4C': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB4D': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB4E': return bit+'1,(IY+'+p2+')';
	  	case 'FDCB4F': return bit+'1,(IY+'+p2+')*';
	  	case 'FDCB50': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB51': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB52': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB53': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB54': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB55': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB56': return bit+'2,(IY+'+p2+')';
	  	case 'FDCB57': return bit+'2,(IY+'+p2+')*';
	  	case 'FDCB58': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB59': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB5A': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB5B': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB5C': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB5D': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB5E': return bit+'3,(IY+'+p2+')';
	  	case 'FDCB5F': return bit+'3,(IY+'+p2+')*';
	  	case 'FDCB60': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB61': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB62': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB63': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB64': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB65': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB66': return bit+'4,(IY+'+p2+')';
	  	case 'FDCB67': return bit+'4,(IY+'+p2+')*';
	  	case 'FDCB68': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB69': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB6A': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB6B': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB6C': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB6D': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB6E': return bit+'5,(IY+'+p2+')';
	  	case 'FDCB6F': return bit+'5,(IY+'+p2+')*';
	  	case 'FDCB70': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB71': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB72': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB73': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB74': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB75': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB76': return bit+'6,(IY+'+p2+')';
	  	case 'FDCB77': return bit+'6,(IY+'+p2+')*';
	  	case 'FDCB78': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB79': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB7A': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB7B': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB7C': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB7D': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB7E': return bit+'7,(IY+'+p2+')';
	  	case 'FDCB7F': return bit+'7,(IY+'+p2+')*';
	  	case 'FDCB80': return res+'0,(IY+'+p2+'),B';
	  	case 'FDCB81': return res+'0,(IY+'+p2+'),C';
	  	case 'FDCB82': return res+'0,(IY+'+p2+'),D';
	  	case 'FDCB83': return res+'0,(IY+'+p2+'),E';
	  	case 'FDCB84': return res+'0,(IY+'+p2+'),H';
	  	case 'FDCB85': return res+'0,(IY+'+p2+'),L';
	  	case 'FDCB86': return res+'0,(IY+'+p2+')';
	  	case 'FDCB87': return res+'0,(IY+'+p2+'),A';
	  	case 'FDCB88': return res+'1,(IY+'+p2+'),B';
	  	case 'FDCB89': return res+'1,(IY+'+p2+'),C';
	  	case 'FDCB8A': return res+'1,(IY+'+p2+'),D';
	  	case 'FDCB8B': return res+'1,(IY+'+p2+'),E';
	  	case 'FDCB8C': return res+'1,(IY+'+p2+'),H';
	  	case 'FDCB8D': return res+'1,(IY+'+p2+'),L';
	  	case 'FDCB8E': return res+'1,(IY+'+p2+')';
	  	case 'FDCB8F': return res+'1,(IY+'+p2+'),A';
	  	case 'FDCB90': return res+'2,(IY+'+p2+'),B';
	  	case 'FDCB91': return res+'2,(IY+'+p2+'),C';
	  	case 'FDCB92': return res+'2,(IY+'+p2+'),D';
	  	case 'FDCB93': return res+'2,(IY+'+p2+'),E';
	  	case 'FDCB94': return res+'2,(IY+'+p2+'),H';
	  	case 'FDCB95': return res+'2,(IY+'+p2+'),L';
	  	case 'FDCB96': return res+'2,(IY+'+p2+')';
	  	case 'FDCB97': return res+'2,(IY+'+p2+'),A';
	  	case 'FDCB98': return res+'3,(IY+'+p2+'),B';
	  	case 'FDCB99': return res+'3,(IY+'+p2+'),C';
	  	case 'FDCB9A': return res+'3,(IY+'+p2+'),D';
	  	case 'FDCB9B': return res+'3,(IY+'+p2+'),E';
	  	case 'FDCB9C': return res+'3,(IY+'+p2+'),H';
	  	case 'FDCB9D': return res+'3,(IY+'+p2+'),L';
	  	case 'FDCB9E': return res+'3,(IY+'+p2+')';
	  	case 'FDCB9F': return res+'3,(IY+'+p2+'),A';
	  	case 'FDCBA0': return res+'4,(IY+'+p2+'),B';
	  	case 'FDCBA1': return res+'4,(IY+'+p2+'),C';
	  	case 'FDCBA2': return res+'4,(IY+'+p2+'),D';
	  	case 'FDCBA3': return res+'4,(IY+'+p2+'),E';
	  	case 'FDCBA4': return res+'4,(IY+'+p2+'),H';
	  	case 'FDCBA5': return res+'4,(IY+'+p2+'),L';
	  	case 'FDCBA6': return res+'4,(IY+'+p2+')';
	  	case 'FDCBA7': return res+'4,(IY+'+p2+'),A';
	  	case 'FDCBA8': return res+'5,(IY+'+p2+'),B';
	  	case 'FDCBA9': return res+'5,(IY+'+p2+'),C';
	  	case 'FDCBAA': return res+'5,(IY+'+p2+'),D';
	  	case 'FDCBAB': return res+'5,(IY+'+p2+'),E';
	  	case 'FDCBAC': return res+'5,(IY+'+p2+'),H';
	  	case 'FDCBAD': return res+'5,(IY+'+p2+'),L';
	  	case 'FDCBAE': return res+'5,(IY+'+p2+')';
	  	case 'FDCBAF': return res+'5,(IY+'+p2+'),A';
	  	case 'FDCBB0': return res+'6,(IY+'+p2+'),B';
	  	case 'FDCBB1': return res+'6,(IY+'+p2+'),C';
	  	case 'FDCBB2': return res+'6,(IY+'+p2+'),D';
	  	case 'FDCBB3': return res+'6,(IY+'+p2+'),E';
	  	case 'FDCBB4': return res+'6,(IY+'+p2+'),H';
	  	case 'FDCBB5': return res+'6,(IY+'+p2+'),L';
	  	case 'FDCBB6': return res+'6,(IY+'+p2+')';
	  	case 'FDCBB7': return res+'6,(IY+'+p2+'),A';
	  	case 'FDCBB8': return res+'7,(IY+'+p2+'),B';
	  	case 'FDCBB9': return res+'7,(IY+'+p2+'),C';
	  	case 'FDCBBA': return res+'7,(IY+'+p2+'),D';
	  	case 'FDCBBB': return res+'7,(IY+'+p2+'),E';
	  	case 'FDCBBC': return res+'7,(IY+'+p2+'),H';
	  	case 'FDCBBD': return res+'7,(IY+'+p2+'),L';
	  	case 'FDCBBE': return res+'7,(IY+'+p2+')';
	  	case 'FDCBBF': return res+'7,(IY+'+p2+'),A';
	  	case 'FDCBC0': return set+'0,(IY+'+p2+'),B';
	  	case 'FDCBC1': return set+'0,(IY+'+p2+'),C';
	  	case 'FDCBC2': return set+'0,(IY+'+p2+'),D';
	  	case 'FDCBC3': return set+'0,(IY+'+p2+'),E';
	  	case 'FDCBC4': return set+'0,(IY+'+p2+'),H';
	  	case 'FDCBC5': return set+'0,(IY+'+p2+'),L';
	  	case 'FDCBC6': return set+'0,(IY+'+p2+')';
	  	case 'FDCBC7': return set+'0,(IY+'+p2+'),A';
	  	case 'FDCBC8': return set+'1,(IY+'+p2+'),B';
	  	case 'FDCBC9': return set+'1,(IY+'+p2+'),C';
	  	case 'FDCBCA': return set+'1,(IY+'+p2+'),D';
	  	case 'FDCBCB': return set+'1,(IY+'+p2+'),E';
	  	case 'FDCBCC': return set+'1,(IY+'+p2+'),H';
	  	case 'FDCBCD': return set+'1,(IY+'+p2+'),L';
	  	case 'FDCBCE': return set+'1,(IY+'+p2+')';
	  	case 'FDCBCF': return set+'1,(IY+'+p2+'),A';
	  	case 'FDCBD0': return set+'2,(IY+'+p2+'),B';
	  	case 'FDCBD1': return set+'2,(IY+'+p2+'),C';
	  	case 'FDCBD2': return set+'2,(IY+'+p2+'),D';
	  	case 'FDCBD3': return set+'2,(IY+'+p2+'),E';
	  	case 'FDCBD4': return set+'2,(IY+'+p2+'),H';
	  	case 'FDCBD5': return set+'2,(IY+'+p2+'),L';
	  	case 'FDCBD6': return set+'2,(IY+'+p2+')';
	  	case 'FDCBD7': return set+'2,(IY+'+p2+'),A';
	  	case 'FDCBD8': return set+'3,(IY+'+p2+'),B';
	  	case 'FDCBD9': return set+'3,(IY+'+p2+'),C';
	  	case 'FDCBDA': return set+'3,(IY+'+p2+'),D';
	  	case 'FDCBDB': return set+'3,(IY+'+p2+'),E';
	  	case 'FDCBDC': return set+'3,(IY+'+p2+'),H';
	  	case 'FDCBDD': return set+'3,(IY+'+p2+'),L';
	  	case 'FDCBDE': return set+'3,(IY+'+p2+')';
	  	case 'FDCBDF': return set+'3,(IY+'+p2+'),A';
	  	case 'FDCBE0': return set+'4,(IY+'+p2+'),B';
	  	case 'FDCBE1': return set+'4,(IY+'+p2+'),C';
	  	case 'FDCBE2': return set+'4,(IY+'+p2+'),D';
	  	case 'FDCBE3': return set+'4,(IY+'+p2+'),E';
	  	case 'FDCBE4': return set+'4,(IY+'+p2+'),H';
	  	case 'FDCBE5': return set+'4,(IY+'+p2+'),L';
	  	case 'FDCBE6': return set+'4,(IY+'+p2+')';
	  	case 'FDCBE7': return set+'4,(IY+'+p2+'),A';
	  	case 'FDCBE8': return set+'5,(IY+'+p2+'),B';
	  	case 'FDCBE9': return set+'5,(IY+'+p2+'),C';
	  	case 'FDCBEA': return set+'5,(IY+'+p2+'),D';
	  	case 'FDCBEB': return set+'5,(IY+'+p2+'),E';
	  	case 'FDCBEC': return set+'5,(IY+'+p2+'),H';
	  	case 'FDCBED': return set+'5,(IY+'+p2+'),L';
	  	case 'FDCBEE': return set+'5,(IY+'+p2+')';
	  	case 'FDCBEF': return set+'5,(IY+'+p2+'),A';
	  	case 'FDCBF0': return set+'6,(IY+'+p2+'),B';
	  	case 'FDCBF1': return set+'6,(IY+'+p2+'),C';
	  	case 'FDCBF2': return set+'6,(IY+'+p2+'),D';
	  	case 'FDCBF3': return set+'6,(IY+'+p2+'),E';
	  	case 'FDCBF4': return set+'6,(IY+'+p2+'),H';
	  	case 'FDCBF5': return set+'6,(IY+'+p2+'),L';
	  	case 'FDCBF6': return set+'6,(IY+'+p2+')';
	  	case 'FDCBF7': return set+'6,(IY+'+p2+'),A';
	  	case 'FDCBF8': return set+'7,(IY+'+p2+'),B';
	  	case 'FDCBF9': return set+'7,(IY+'+p2+'),C';
	  	case 'FDCBFA': return set+'7,(IY+'+p2+'),D';
	  	case 'FDCBFB': return set+'7,(IY+'+p2+'),E';
	  	case 'FDCBFC': return set+'7,(IY+'+p2+'),H';
	  	case 'FDCBFD': return set+'7,(IY+'+p2+'),L';
	  	case 'FDCBFE': return set+'7,(IY+'+p2+')';
	  	case 'FDCBFF': return set+'7,(IY+'+p2+'),A'; 	    
	  	default:       return '';
	  }
	}


var toHexN = function(n,d) {
	var s = n.toString(16);
	while (s.length <d) {s = '0'+s;}
	return s.toUpperCase();
};

var toHex2 = function(n) {return toHexN(n & 0xff,2);};
var toHex4 = function(n) {return toHexN(n,4);};



 window.CPUDZ80 = {
 	// 5 codes
 	disasm: function(i,a,b,c,d, pc) {
 		var sx = code1[i];
 		if (sx) return [sx,1];
	 	sx = code2(toHex2(i),toHex2(a),pc);
		if (sx) return [sx,2];
	 	sx = code3(toHex2(i),toHex2(a),toHex2(b));
		if (sx) return [sx,3];
	 	sx = code4(toHex2(i),toHex2(a),toHex2(b), toHex2(c));
		if (sx) return [sx,4];
		if (!sx) return ['UNKNOWN',0];
 	}
 };

})(window);